### PR TITLE
Update Python Version

### PR DESCRIPTION
**Pull request by iLtc**
We are currently using 3.6.9 for our local development. However, this version is not supported by IBM Cloud.

I have updated the python version to 3.6.12. Since this is a minor update, no change needs to make on our local machine.

## Checklist:

- [x] I have attached this PR to an issue/user story

### CODE REVIEW

**Review by KHafner — APPROVED** [review]

**Comment by KHafner** [comment]
What issue is this connected to?

**Comment by iLtc** [comment]
> What issue is this connected to?

My bad. I just connected it.

**Review by gauridhawan — APPROVED** [review]

**Comment by KHafner** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/b5c2987e-b3d1-4601-9f28-34419832137d?env_id=ibm:yp:us-south "nyu-shopcart-service-f20-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/c869c127-ceda-423d-80b8-f74ee52b7378 "nyu-shopcart-service-f20-pipeline") deployed [shopcarts](https://github.com/NYU-DevOps2020-shopcarts/shopcarts/releases/tag/deploy-ibm-yp-us-south-kfh226-nyu.edu-dev-20201103-180801 "deploy-ibm-yp-us-south-kfh226-nyu.edu-dev-20201103-180801") to [dev](https://console.bluemix.net/apps/9acc4a4a-3e86-4e84-9d4f-87cc363a812b?env_id=ibm:yp:us-south "ibm:yp:us-south:kfh226@nyu.edu:dev"), including commit 37e5f504294aaf4a8924d9c2ca2dd9320b340bfc

**Comment by KHafner** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/b5c2987e-b3d1-4601-9f28-34419832137d?env_id=ibm:yp:us-south "nyu-shopcart-service-f20-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/c869c127-ceda-423d-80b8-f74ee52b7378 "nyu-shopcart-service-f20-pipeline") deployed [shopcarts](https://github.com/NYU-DevOps2020-shopcarts/shopcarts/releases/tag/deploy-ibm-yp-us-south-kfh226-nyu.edu-prod-20201208-144028 "deploy-ibm-yp-us-south-kfh226-nyu.edu-prod-20201208-144028") to [prod](https://console.bluemix.net/apps/ac06a6b3-040d-43d7-b290-6bfbba3f8c41?env_id=ibm:yp:us-south "ibm:yp:us-south:kfh226@nyu.edu:prod"), including commit 37e5f504294aaf4a8924d9c2ca2dd9320b340bfc

**Pull request merged**
