### PR TITLE
Place order

### PR DESCRIPTION
**Pull request by KHafner**
# Pull Request Template

## Checklist:

- [X] I have written test cases for this change, and my code passed the test
- [X] I have attached this PR to an issue/user story

### CODE REVIEW

**Comment by KHafner** [comment]
One potential problem here is that we are using a float for the item amount, whereas the orders team is using int, should we change it back? 

Also I couldn't come up with a way to create a test case for getting a 400 error when creating a new order since we have a lot of checks to prevent invalid shopcart items and it checks if the shopcart is empty before placing the order. Does anyone have a suggestion?

**Comment by gauridhawan** [comment]
@KHafner I'm not sure, do you think it will be an easier change at our end or at theirs?

**Comment by KHafner** [comment]
The orders team has a failing build right now and their service is down, so this PR needs to wait until that is resolved

**Review by iLtc — APPROVED** [review]
LGTM, thanks!

**Review by jules203 — APPROVED** [review]
great job!

**Comment by KHafner** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/b5c2987e-b3d1-4601-9f28-34419832137d?env_id=ibm:yp:us-south "nyu-shopcart-service-f20-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/c869c127-ceda-423d-80b8-f74ee52b7378 "nyu-shopcart-service-f20-pipeline") deployed [shopcarts](https://github.com/NYU-DevOps2020-shopcarts/shopcarts/releases/tag/deploy-ibm-yp-us-south-kfh226-nyu.edu-dev-20201209-013546 "deploy-ibm-yp-us-south-kfh226-nyu.edu-dev-20201209-013546") to [dev](https://console.bluemix.net/apps/acaa0f76-8448-48eb-9168-305d9b4de99c?env_id=ibm:yp:us-south "ibm:yp:us-south:kfh226@nyu.edu:dev"), including commit 37f4d792433f1df3a27c85b74835490ae90025fe

**Comment by KHafner** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/b5c2987e-b3d1-4601-9f28-34419832137d?env_id=ibm:yp:us-south "nyu-shopcart-service-f20-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/c869c127-ceda-423d-80b8-f74ee52b7378 "nyu-shopcart-service-f20-pipeline") deployed [shopcarts](https://github.com/NYU-DevOps2020-shopcarts/shopcarts/releases/tag/deploy-ibm-yp-us-south-kfh226-nyu.edu-prod-20201209-014130 "deploy-ibm-yp-us-south-kfh226-nyu.edu-prod-20201209-014130") to [prod](https://console.bluemix.net/apps/ac06a6b3-040d-43d7-b290-6bfbba3f8c41?env_id=ibm:yp:us-south "ibm:yp:us-south:kfh226@nyu.edu:prod"), including commit 37f4d792433f1df3a27c85b74835490ae90025fe

**Pull request merged**
