### PR TITLE
Fix Syntax

### PR DESCRIPTION
**Pull request by iLtc**
This PR tries to fix as many syntax issues as possible.

## Checklist:

- [x] I have attached this PR to an issue/user story

### CODE REVIEW

**Review by KHafner — APPROVED** [review]
Looks great, thanks!

**Review by nonococoleo — APPROVED** [review]
fantastic work! thx

**Comment by KHafner** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/b5c2987e-b3d1-4601-9f28-34419832137d?env_id=ibm:yp:us-south "nyu-shopcart-service-f20-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/c869c127-ceda-423d-80b8-f74ee52b7378 "nyu-shopcart-service-f20-pipeline") deployed [shopcarts](https://github.com/NYU-DevOps2020-shopcarts/shopcarts/releases/tag/deploy-ibm-yp-us-south-kfh226-nyu.edu-dev-20201208-142146 "deploy-ibm-yp-us-south-kfh226-nyu.edu-dev-20201208-142146") to [dev](https://console.bluemix.net/apps/acaa0f76-8448-48eb-9168-305d9b4de99c?env_id=ibm:yp:us-south "ibm:yp:us-south:kfh226@nyu.edu:dev"), including commit 20ecc94e11e27a0daedc3d66dfa3e1359771d400

**Comment by KHafner** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/b5c2987e-b3d1-4601-9f28-34419832137d?env_id=ibm:yp:us-south "nyu-shopcart-service-f20-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/c869c127-ceda-423d-80b8-f74ee52b7378 "nyu-shopcart-service-f20-pipeline") deployed [shopcarts](https://github.com/NYU-DevOps2020-shopcarts/shopcarts/releases/tag/deploy-ibm-yp-us-south-kfh226-nyu.edu-prod-20201208-144028 "deploy-ibm-yp-us-south-kfh226-nyu.edu-prod-20201208-144028") to [prod](https://console.bluemix.net/apps/ac06a6b3-040d-43d7-b290-6bfbba3f8c41?env_id=ibm:yp:us-south "ibm:yp:us-south:kfh226@nyu.edu:prod"), including commit 20ecc94e11e27a0daedc3d66dfa3e1359771d400

**Pull request merged**
