### PR TITLE
added create shopcart BDD test

### PR DESCRIPTION
**Pull request by KHafner**
# Pull Request Template

## Checklist:

- [X] I have written test cases for this change, and my code passed the test
- [X] I have updated documentation to reflect this change
- [X] I have attached this PR to an issue/user story

### CODE REVIEW

**Review by nonococoleo — APPROVED** [review]

**Review by iLtc — APPROVED** [review]
I will approve this for now, but we rewrite the UI and JS in another branch. 
We will need to check this again after that change gets merged.

**Comment by iLtc** [comment]
I merged the latest UI to this branch and updated the ids to match the test cases. 

This branch can pass the BDD tests now.

**Comment by KHafner** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/b5c2987e-b3d1-4601-9f28-34419832137d?env_id=ibm:yp:us-south "nyu-shopcart-service-f20-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/c869c127-ceda-423d-80b8-f74ee52b7378 "nyu-shopcart-service-f20-pipeline") deployed [shopcarts](https://github.com/NYU-DevOps2020-shopcarts/shopcarts/releases/tag/deploy-ibm-yp-us-south-kfh226-nyu.edu-dev-20201115-181755 "deploy-ibm-yp-us-south-kfh226-nyu.edu-dev-20201115-181755") to [dev](https://console.bluemix.net/apps/4aa42608-55fd-40d6-b27b-d99aa18a0658?env_id=ibm:yp:us-south "ibm:yp:us-south:kfh226@nyu.edu:dev"), including commit 483b649af108ddb20b05279edac1401d2facb8a9

**Comment by KHafner** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/b5c2987e-b3d1-4601-9f28-34419832137d?env_id=ibm:yp:us-south "nyu-shopcart-service-f20-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/c869c127-ceda-423d-80b8-f74ee52b7378 "nyu-shopcart-service-f20-pipeline") deployed [shopcarts](https://github.com/NYU-DevOps2020-shopcarts/shopcarts/releases/tag/deploy-ibm-yp-us-south-kfh226-nyu.edu-prod-20201208-144028 "deploy-ibm-yp-us-south-kfh226-nyu.edu-prod-20201208-144028") to [prod](https://console.bluemix.net/apps/ac06a6b3-040d-43d7-b290-6bfbba3f8c41?env_id=ibm:yp:us-south "ibm:yp:us-south:kfh226@nyu.edu:prod"), including commit 483b649af108ddb20b05279edac1401d2facb8a9

**Pull request merged**
